job_analysis:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: tir103-job-analysis
      dataset: final_data
      threads: 4
      keyfile: /opt/airflow/keys/service-account.json
      timeout_seconds: 300
      location: asia-east1
      priority: interactive
