# airflow/dbt_project/dbt_project.yml
name: 'job_analysis'
version: '1.0.0'
config-version: 2

profile: 'job_analysis'

log-path: "/tmp/dbt_logs"  # 設置到 /tmp 避免權限問題
target-path: "/opt/airflow/logs/dbt/target"
packages-install-path: "/opt/airflow/logs/dbt/packages"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_analysis:
    staging:
      +materialized: view
      +tags: ['staging']
      
    # intermediate:
    #   +materialized: table
    #   +tags: ['intermediate']

    mart:
      +materialized: table
      +tags: ['mart']
