version: 2

models:
  - name: stg_job
    description: "Cleans and labels raw job data, marking jobs with null salaries as 'negotiable'."
    columns:
      - name: source
        description: "Data source"
      - name: report_date
        description: "Report date"
      - name: jobtitle
        description: "Job title"
      - name: company_name
        description: "Company name"
      - name: education
        description: "Education requirement"
      - name: job_category
        description: "Job category"
      - name: salary
        description: "Salary"
      - name: location_region
        description: "Location region"
      - name: experience
        description: "Experience requirement"
      - name: industry
        description: "Industry"
      - name: tools
        description: "Tools or skills required"
      - name: is_salary_negotiable
        description: "Indicates if the job's salary is negotiable"
      - name: uuid
        description: "Unique identifier, MD5 hash based on report date, job title, company name, location, experience, and tools"
